### ISSUE TITLE
Аккулумирующий таск

### ISSUE THREAD

**Issue by KozlovKV** [KozlovKV/game-life#30]
@PalkinEgor , решил собрать здесь для тебя все имеющиеся таски, которые надо сделать к... Вчера.

**ОЧЕНЬ ВАЖНО!** Теперь псевдокод из ТЗ не опасно для здоровья читать (*надеюсь, по крайней мере*). В нём я описал на чём-то близком к ассемблеру механизм всех вспомогательных функций и почти описал главную функцию. Очень рекомендую пользоваться этим как референсами для тасков 2-4 - https://github.com/KozlovKV/game-life/blob/master/tech-info.md#псевдокод

Собственно, таски:
- [x] Считывание условий жизни и смерти **(приоритет - средний)** - #7 
- [x] Функция циклических инкрементов / декрементов **(приоритет - высокий)** - #11 
- [x] Функции получения и инверсии бита **(приоритет - высочайший)** - #14 
- [x] Функция обработки бита в байте по собранным данным **(приоритет - высокий - делать только после таска над этим)** - #29 

Особняком стоит этот таск - #15 . Собственно, 3 из 4 тасков выше отсылаются именно к нему по своему применению, так что сначала сделай их все

**Comment by KozlovKV** [comment]
@PalkinEgor completed tasks. Merge all results to develop. Continue working with #15
